In [127]:
import os
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt


In [128]:
current_dir = os.getcwd()
training_set = pd.read_csv(r"./files/MNIST/kaggle csv format/mnist_train.csv")
testing_set = pd.read_csv(r"./files/MNIST/kaggle csv format/mnist_test.csv")

In [129]:
#working through numpy
training_set = np.array(training_set)
m1, n1 = training_set.shape # m are pixels p/image, n are number of imgs (785, 60 000)
np.random.shuffle(training_set)
training_set.T
training_set = training_set[0:3000]

x_train = training_set[1:n1]
y_train = training_set[0]

testing_set = np.array(testing_set)
m2, n2 = testing_set.shape # testing set looks funny -> 10 000, 785
np.random.shuffle(testing_set)
testing_set = testing_set[0:2000] # yeah so dont transpose this otherwise the matrices look funny

x_test = testing_set[1:n2]
y_test = testing_set[0]




In [130]:
def init_params(input_size, hidden_size, output_size):
    w1 = np.random.rand(hidden_size, input_size)
    print(w1)
    b1 = np.zeros((hidden_size, 1))

    w2 = np.random.rand(output_size, hidden_size)
    b2 = np.zeros((output_size, 1))

    param = {"w1": w1, "b1": b1, "w2": w2, "b2": b2}

    return param

In [131]:
param = init_params(784, 10, 1)

[[0.75301139 0.03187772 0.86010888 ... 0.18756384 0.64255027 0.66188746]
 [0.63299432 0.37006367 0.52787009 ... 0.02357339 0.26245036 0.47064322]
 [0.54537174 0.85315638 0.98556339 ... 0.81096841 0.817171   0.22167809]
 ...
 [0.94484018 0.45635815 0.42446281 ... 0.89814705 0.92199038 0.84408232]
 [0.76553096 0.28425368 0.12513108 ... 0.31769312 0.29268851 0.09065855]
 [0.65012417 0.45072267 0.32614105 ... 0.26667753 0.30727506 0.50280765]]


In [132]:
def ReLU(x):
    return x * (x>0)

def dReLU(x):
    return 1*(x>=0)

In [139]:
def forwardFeed(x, param):
    # retrieve parameters
    w1 = param["w1"]
    b1 = param["b1"]
    w2 = param["w2"]
    b2 = param["b2"]

    # activate hidden layer
    z1 = np.dot(w1, x_train)+b1
    a1 = ReLU(z1)
    

In [141]:
forwardFeed(x_train, param)

[[1712.42650927    0.            0.         ...    0.
     0.            0.        ]
 [1782.71616415    0.            0.         ...    0.
     0.            0.        ]
 [1770.1046188     0.            0.         ...    0.
     0.            0.        ]
 ...
 [1808.78557699    0.            0.         ...    0.
     0.            0.        ]
 [1722.80701746    0.            0.         ...    0.
     0.            0.        ]
 [1824.85337856    0.            0.         ...    0.
     0.            0.        ]]
