In [175]:
import os
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt


In [176]:
current_dir = os.getcwd()
training_set = pd.read_csv(r"./files/MNIST/kaggle csv format/mnist_train.csv")
testing_set = pd.read_csv(r"./files/MNIST/kaggle csv format/mnist_test.csv")

In [177]:
#working through numpy
training_set = np.array(training_set)
m1, n1 = training_set.shape # m are pixels p/image, n are number of imgs (785, 60 000)
np.random.shuffle(training_set)
training_set.T
training_set = training_set[0:3000]
print(m1, n1) #debug

x_train = training_set[1:n1]
y_train = training_set[0]

testing_set = np.array(testing_set)
m2, n2 = testing_set.shape # testing set looks funny -> 10 000, 785
np.random.shuffle(testing_set)
testing_set = testing_set[0:2000] # yeah so dont transpose this otherwise the matrices look funny
print(m2, n2) #debug

x_test = testing_set[1:n2]
y_test = testing_set[0]




60000 785
10000 785


In [178]:
def init_params(input_size, hidden_size, output_size):
    w1 = np.random.rand(hidden_size, input_size)
    print(w1) # debug
    b1 = np.zeros((hidden_size, 1))

    w2 = np.random.rand(output_size, hidden_size)
    b2 = np.zeros((output_size, 1))

    param = {"w1": w1, "b1": b1, "w2": w2, "b2": b2}

    return param

In [179]:
param = init_params(785, 10, 1)

[[0.32153361 0.74906815 0.2019563  ... 0.341128   0.60493938 0.52221156]
 [0.4615925  0.23932639 0.6234778  ... 0.56589329 0.43333052 0.32953597]
 [0.08958368 0.7806521  0.31323415 ... 0.78705523 0.12660285 0.27575459]
 ...
 [0.81525066 0.01749234 0.09636997 ... 0.3057534  0.9084565  0.80346029]
 [0.18516954 0.07404363 0.20921432 ... 0.89359333 0.58831318 0.71537253]
 [0.31748651 0.77669451 0.86243266 ... 0.60046539 0.23981936 0.77829607]]


In [180]:
def ReLU(x):
    return x*(x>0)

def dReLU(x):
    return 1*(x>=0)

In [181]:
def forwardFeed(x, param):
    # retrieve parameters
    w1 = param["w1"]
    b1 = param["b1"]
    w2 = param["w2"]
    b2 = param["b2"]

    # activate hidden layer
    z1 = np.dot(w1, x_train.T)+b1
    a1 = ReLU(z1)

    z2 = np.dot(w2, a1)+b2
    a2 = ReLU(z2)

    cache = {"z1": z1, "a1": a1, "z2": z2, "a2": a2}
    return a2, cache
    

In [182]:
a2, cache = forwardFeed(x_train, param)